### ISSUE TITLE
Sentinel Test failed

### ISSUE THREAD

**Issue by mercadolino** [monacocoin-net/sentinel#1]
Hello, I am setting up a masternode with the new wallet 12.2 and when running the sentinel test I am getting this error:

test/integration/test_jsonrpc.py:34:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
lib/monoecid.py:42: in rpc_command
    return self.rpc_connection.__getattr__(params[0])(*params[1:])
venv/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py:136: in __call__
    'Content-type': 'application/json'})
/usr/lib/python2.7/httplib.py:1057: in request
    self._send_request(method, url, body, headers)
/usr/lib/python2.7/httplib.py:1097: in _send_request
    self.endheaders(body)
/usr/lib/python2.7/httplib.py:1053: in endheaders
    self._send_output(message_body)
/usr/lib/python2.7/httplib.py:897: in _send_output
    self.send(msg)
/usr/lib/python2.7/httplib.py:859: in send
    self.connect()
/usr/lib/python2.7/httplib.py:836: in connect
    self.timeout, self.source_address)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

address = ('5hmv$y8xgfsgl', 80), timeout = 30, source_address = None

    def create_connection(address, timeout=_GLOBAL_DEFAULT_TIMEOUT,
                          source_address=None):
        """Connect to *address* and return the socket object.

        Convenience function.  Connect to *address* (a 2-tuple ``(host,
        port)``) and return the socket object.  Passing the optional
        *timeout* parameter will set the timeout on the socket instance
        before attempting to connect.  If no *timeout* is supplied, the
        global default timeout setting returned by :func:`getdefaulttimeout`
        is used.  If *source_address* is set it must be a tuple of (host, port)
        for the socket to bind as a source address before making the connection.
        A host of '' or port 0 tells the OS to use the default.
        """

        host, port = address
        err = None
>       for res in getaddrinfo(host, port, 0, SOCK_STREAM):
E       gaierror: [Errno -2] Name or service not known

/usr/lib/python2.7/socket.py:557: gaierror
============================================================================ 1 failed, 19 passed in 0.45 seconds ============================================================================
u

**Comment by Yoyae** [comment]
Sorry to answer that late, you issue might have been solve already. If not, check the new version.
I'm closing this. If you feel the new version doesn't address the issue feel free to open a new one.
